# Generated by Django 2.1.5 on 2021-01-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='zoom',
            field=models.IntegerField(default=5),
        ),
    ]
