# Generated by Django 2.1.5 on 2021-01-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0002_auto_20210103_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='style',
            field=models.CharField(choices=[('streets', 'streets-v11'), ('light', 'light-v10'), ('dark', 'dark-v10'), ('outdoors', 'outdoors-v11'), ('satellite', 'satellite-v9')], default='streets', max_length=100),
        ),
    ]
