# Generated by Django 2.1.5 on 2021-01-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0003_auto_20210105_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='style',
            field=models.CharField(choices=[('streets-v11', 'streets'), ('light-v10', 'light'), ('dark-v10', 'dark'), ('outdoors-v11', 'outdoors'), ('satellite-v9', 'satellite')], default='streets', max_length=100),
        ),
    ]
