# Generated by Django 2.1.5 on 2021-01-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0004_auto_20210110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='zoom',
            field=models.FloatField(default=5),
        ),
    ]
