# Generated by Django 2.1.5 on 2021-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0005_auto_20210121_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemap',
            name='thumbnail',
            field=models.ImageField(default='default_map.png', upload_to=''),
        ),
    ]
