# Generated by Django 2.1.5 on 2021-02-09 13:54

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0009_auto_20210208_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='cogopoint',
            name='setID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='cogopoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, 0.0), geography=True, srid=4326),
        ),
    ]
