# Generated by Django 2.1.5 on 2021-02-09 15:35

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0010_auto_20210209_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogopoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(x=0.0, y=0.0, z=0.0), geography=True, srid=4326),
        ),
    ]
