# Generated by Django 2.1.5 on 2021-02-09 16:08

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0012_auto_20210209_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogopoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, 0.0), dim=3, srid=4326),
        ),
    ]
