# Generated by Django 2.1.5 on 2021-02-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0014_auto_20210209_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='cogopointset',
            name='basemap',
            field=models.ManyToManyField(to='basemap.Basemap'),
        ),
    ]
