# Generated by Django 2.1.5 on 2021-02-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0015_cogopointset_basemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cogopointset',
            name='basemap',
        ),
        migrations.AddField(
            model_name='basemap',
            name='pointsets',
            field=models.ManyToManyField(to='basemap.COGOPointSet'),
        ),
    ]
