# Generated by Django 2.1.5 on 2021-02-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0016_auto_20210209_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='pointsets',
            field=models.ManyToManyField(blank=True, to='basemap.COGOPointSet'),
        ),
    ]
